---
# Handles containers and k8s manifests state at the dirs specified below
- hosts: all
  become: yes
  vars_files:
    - secret_vars.yml
  vars:
    docker_images_path: "../../kubernetes/dockerfiles"
    k8s_manifests_path: "../../kubernetes/base/manifests"
    helm_charts_path: "../../kubernetes/base/helm" 
    registry_name: "local-registry"
    registry_port: "5000"
    ansible_become_pass: "{{ ansible_become_pass }}"
    helm_deployments:
      - name: "white"
        namespace: "white"
        chart: "oci://registry-1.docker.io/bitnamicharts/nginx"
        repository: ""
        values_file: "{{ helm_charts_path }}/white/values.yaml"
      - name: "black"
        namespace: "black"
        chart: "oci://registry-1.docker.io/bitnamicharts/nginx"
        repository: ""
        values_file: "{{ helm_charts_path }}/black/values.yaml"
      - name: "metrics-server"
        namespace: "kube-system"
        chart: "metrics-server/metrics-server"
        repository: "metrics-server"
        values_file: "{{ helm_charts_path }}/metrics-server/values.yaml"
      - name: "ingress-nginx"
        namespace: "ingress-nginx"
        chart: "ingress-nginx/ingress-nginx"
        repository: "https://kubernetes.github.io/ingress-nginx"
        create_namespace: true
        values_file: "{{ helm_charts_path }}/ingress-nginx/values.yaml"
  
  pre_tasks:
    # Check Kubernetes initialization
    - name: Check if Kubernetes is initialized
      stat:
        path: /etc/kubernetes/admin.conf
      register: k8s_check

    - name: Fail if Kubernetes is not initialized
      fail:
        msg: "Kubernetes is not initialized. Please run bootstrap.yml first"
      when: not k8s_check.stat.exists

    # Container pre-tasks:
    - name: Check if Docker is installed locally
      command: docker --version
      delegate_to: localhost
      become: no
      register: docker_check
      ignore_errors: yes
      changed_when: false

    - name: Fail if Docker is not installed
      fail:
        msg: "Docker is not installed on localhost. Please install Docker first."
      when: docker_check.rc != 0
      delegate_to: localhost
      become: no

    - name: Check if Docker is running locally
      command: docker info
      delegate_to: localhost
      become: no
      register: docker_running
      ignore_errors: yes
      changed_when: false

    - name: Fail if Docker is not running
      fail:
        msg: "Docker is not running on localhost. Please start Docker service."
      when: docker_running.rc != 0
      delegate_to: localhost
      become: no

    - name: Check if registry container exists
      shell: docker ps -a --filter name={{ registry_name }} --format "{% raw %}{{.Names}}{% endraw %}"
      delegate_to: localhost
      become: no
      register: registry_exists
      changed_when: false

    - name: Check if registry is running
      shell: docker ps --filter name={{ registry_name }} --format "{% raw %}{{.Names}}{% endraw %}"
      delegate_to: localhost
      become: no
      register: registry_running
      changed_when: false

    - name: Start registry if exists but not running
      command: docker start {{ registry_name }}
      delegate_to: localhost
      become: no
      when: 
        - registry_exists.stdout == registry_name
        - registry_running.stdout != registry_name

    - name: Create registry if doesn't exist
      command: docker run -d --restart always -p {{ registry_port }}:5000 --name {{ registry_name }} registry:2
      delegate_to: localhost
      become: no
      when: registry_exists.stdout != registry_name

    - name: Wait for registry to be ready
      uri:
        url: "http://localhost:{{ registry_port }}/v2/_catalog"
        method: GET
      register: registry_health
      until: registry_health.status == 200
      retries: 5
      delay: 2
      delegate_to: localhost
      become: no

    - name: Ensure required python packages are installed
      apt:
        name: 
          - python3-pip
          - python3-dev
          - python3-kubernetes
        state: present
        update_cache: yes
      delegate_to: localhost
      become: yes

  
  tasks:

    # CUSTOM CONTAINER FLOW:
    # Always rebuilds all images, I've tried tracking file content, it's cumbersome
    # Probably would need other method than ansible
    - name: Find all Dockerfiles
      find:
        paths: "{{ docker_images_path }}"
        patterns: "Dockerfile"
        recurse: yes
      delegate_to: localhost
      become: no
      register: dockerfiles
    
    - name: Build Docker images
      docker_image:
        build:
          path: "{{ item.path | dirname }}"
          pull: yes
        name: "localhost:{{ registry_port }}/{{ item.path | dirname | basename }}"
        tag: latest
        source: build
        force_source: yes
      loop: "{{ dockerfiles.files }}"
      delegate_to: localhost
      become: no
        
    - name: Save Docker images
      shell: |
        docker save -o "/tmp/{{ item.path | dirname | basename }}.tar" \
        localhost:5000/{{ item.path | dirname | basename }}:latest
      loop: "{{ dockerfiles.files }}"
      delegate_to: localhost
      become: no
      changed_when: false
    
    - name: Copy image to remote host
      copy:
        src: "/tmp/{{ item.path | dirname | basename }}.tar"
        dest: "/tmp/{{ item.path | dirname | basename }}.tar"
      loop: "{{ dockerfiles.files }}"
      delegate_to: k8s_master
      become: yes
    
    - name: Remove existing image from containerd
      shell: |
        ctr -n=k8s.io image rm localhost:5000/{{ item.path | dirname | basename }}:latest || true
      loop: "{{ dockerfiles.files }}"
      delegate_to: k8s_master
      become: yes
      changed_when: false
    
    - name: Import image to containerd
      shell: |
        ctr -n=k8s.io images import "/tmp/{{ item.path | dirname | basename }}.tar"
      loop: "{{ dockerfiles.files }}"
      delegate_to: k8s_master
      become: yes
      changed_when: false

#
#    #  REPO CONTAINER FLOW (to fix hetzner can't reach k8s.io)
#    - name: Prepare Kubernetes images locally
#      block:
#        - name: Create local image download directory
#          file:
#            path: /tmp/k8s-images
#            state: directory
#          delegate_to: localhost
#
#    - name: Pull and save Kubernetes images locally
#      shell: |
#        #!/bin/bash
#        set -e
#        
#        images=(
#          "registry.k8s.io/metrics-server/metrics-server:v0.7.2"
#          "registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.5.0"
#        )
#        
#        for image in "${images[@]}"; do
#          # Pull with platform spec
#          ctr -n=k8s.io image pull --platform linux/amd64 "$image"
#          
#          # Tag with digest if webhook certgen
#          if [[ $image == *"webhook-certgen"* ]]; then
#            ctr -n=k8s.io images tag "$image" "$image@sha256:aaafd456bda110628b2d4ca6296f38731a3aaf0bf7581efae824a41c770a8fc4"
#          fi
#          
#          # Export
#          filename="/tmp/k8s-images/$(echo "$image" | tr '/:@' '_').tar"
#          ctr -n=k8s.io image export "$filename" "$image"
#        done
#        
#        ls -l /tmp/k8s-images/
#      args:
#        executable: /bin/bash
#      delegate_to: localhost
#      register: image_pull_result 
#      changed_when: false
# 
#    - name: Find downloaded image files
#      find:
#        paths: /tmp/k8s-images
#        patterns: '*.tar'
#      delegate_to: localhost
#      register: image_files
#
#    - name: Ensure images directory exists on remote
#      file:
#        path: /tmp/k8s-images
#        state: directory
#
#    - name: Copy images to remote server
#      copy:
#        src: "{{ item.path }}"
#        dest: "/tmp/k8s-images/{{ item.path | basename }}"
#      loop: "{{ image_files.files }}"
#      loop_control:
#        label: "{{ item.path | basename }}"
#
#    - name: Load images on remote server
#      shell: |
#        for image_file in /tmp/k8s-images/*.tar; do
#          ctr -n=k8s.io image import "$image_file"
#        done
#      args:
#        executable: /bin/bash
#
#    - name: Clean up local image files
#      file:
#        path: /tmp/k8s-images
#        state: absent
#      delegate_to: localhost
#
#



    # Created needed dirs in host:
    - name: Create CIS reports directory
      file:
        path: /var/log/cis-linux-and-kube-bench
        state: directory
        mode: '0755'

    # Apply kuberentes config, this updates resources, but doesn't delete:
    - name: Find all K8s manifests
      find:
        paths: "{{ k8s_manifests_path }}"
        patterns: "*.yaml,*.yml"
        recurse: no
      delegate_to: localhost
      become: no
      register: k8s_files

    # Tried with apply --force and doesn't work for pods, using replace,
    # which will DELETE and RECREATE all resources, and apply for NEW resources:    
    - name: Apply namespace manifests first
      ansible.builtin.shell:
        cmd: "kubectl replace --force -f {{ item.path }}"
      loop: "{{ k8s_files.files | selectattr('path', 'match', '.*/namespace_.*') | list }}"
      delegate_to: localhost
      become: no
      register: kubectl_replace_result
      changed_when: "'replaced' in kubectl_replace_result.stdout or 'created' in kubectl_replace_result.stdout"
      ignore_errors: yes
    
    - name: Apply remaining manifests
      ansible.builtin.shell:
        cmd: "kubectl replace --force -f {{ item.path }}"
      loop: "{{ k8s_files.files | rejectattr('path', 'match', '.*/namespace_.*') | list }}"
      delegate_to: localhost
      become: no
      register: kubectl_replace_result
      changed_when: "'replaced' in kubectl_replace_result.stdout or 'created' in kubectl_replace_result.stdout"
      ignore_errors: yes
                      
     
        
    # This two step allows trying graceful apply or forcing if it failed
#    - name: Force apply if previous attempt failed
#      kubernetes.core.k8s:
#        state: present
#        src: "{{ item.item.path }}"
#        apply: yes
#        force: yes
#        wait: yes
#        wait_timeout: 60
#      when: item is failed
#      loop: "{{ apply_result.results }}"
#      delegate_to: localhost
#      become: no
#      vars:
#        ansible_python_interpreter: /usr/bin/python3

  #Adding repos disabled as we are using OCI registry, but it might be needed later 
    - name: Add Helm repositories
      kubernetes.core.helm_repository:
        name: "{{ item.name }}"
        repo_url: "{{ item.url }}"
      loop:
        - name: metrics-server
          url: "https://kubernetes-sigs.github.io/metrics-server/"
        - name: ingress-nginx
          url: "https://kubernetes.github.io/ingress-nginx"
      delegate_to: localhost
      become: no


    # This is not working fine to apply updates, only to create new deployment
    # So to update it requires to manually delete
    # Need to switch to a proper tool to sync the k8s config with the running cluster
    - name: Deploy Helm charts
      kubernetes.core.helm:
        name: "{{ item.name }}"
        chart_ref: "{{ item.chart }}"
        release_namespace: "{{ item.namespace }}"
        create_namespace: true
        values_files: 
          - "{{ item.values_file }}"
        wait: true
        wait_timeout: "300s"  # Changed from 300 to "300s"
        force: false
      loop: "{{ helm_deployments }}"
      delegate_to: localhost
      become: no