nameOverride: "white"
fullnameOverride: "white"

serviceAccount:
  create: true
  name: "white-sa"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: white.pietro.top
      paths:
        - path: /
          pathType: Prefix

# Service override for internal testing, default is LoadBalancer
service:
  type: ClusterIP
  ## @param service.ports.http Port for HTTP
  ports:
    http: 80
    https: 443

persistence:
  enabled: true
  hostPath:
    path: /var/log/cka-tests
    type: DirectoryOrCreate

extraVolumeMounts:
  - name: tests-logs
    mountPath: /var/log/cka-tests
  - name: test-scripts
    mountPath: /usr/local/bin/tests

extraVolumes:
  - name: tests-logs
    hostPath:
      path: /var/log/cka-tests
      type: DirectoryOrCreate
  - name: test-scripts
    configMap:
      name: white-black-tests
      defaultMode: 0755

extraContainers:
  - name: tests
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "/usr/local/bin/tests/run-tests.sh"]
    volumeMounts:
      - name: tests-logs
        mountPath: /var/log/cka-tests
      - name: test-scripts
        mountPath: /usr/local/bin/tests