aws:
  region: ""
  accountId: ""

image:
  repository: ""
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

replicas: 2
