apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-simulator
  labels:
    app: iot-simulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iot-simulator
  template:
    metadata:
      labels:
        app: iot-simulator
    spec:
      containers:
      - name: iot-simulator
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/iot-simulator:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: iot-simulator-config