apiVersion: v1
kind: ConfigMap
metadata:
  name: white-tests
  namespace: white
data:
  run-tests.sh: |
    #!/bin/bash
    
    # Define constants
    COLOR="white"
    LOG_DIR="/var/log/cka-tests-${COLOR}"
    
    # Create the log directory if it doesn't exist
    mkdir -p "${LOG_DIR}"
    
    # Function to install dependencies with retry
    install_deps() {
      if ! (apt-get update && apt-get install -y strace curl apparmor apparmor-utils); then
        echo "Failed to install dependencies at $(date)" >> "${LOG_DIR}/install-error.log"
        return 1
      fi
      return 0
    }

    # Keep trying to install dependencies until successful
    until install_deps; do
      sleep 5
    done

    # Function to enable AppArmor
    enable_apparmor() {
      if ! systemctl is-active apparmor >/dev/null 2>&1; then
        systemctl enable apparmor
        systemctl start apparmor
      fi
    }

    # Try to enable AppArmor if it's not already running
    enable_apparmor

    while true; do
      # Syscall tests
      date >> "${LOG_DIR}/test-syscalls.log"
      strace -c sleep 1 2>> "${LOG_DIR}/test-syscalls.log"
      
      # AppArmor tests
      date >> "${LOG_DIR}/tests-apparmor.logs"
      if aa-status >/dev/null 2>&1; then
        aa-status >> "${LOG_DIR}/tests-apparmor.logs"
      else
        echo "Attempting to enable AppArmor..." >> "${LOG_DIR}/tests-apparmor.logs"
        enable_apparmor
        if aa-status >/dev/null 2>&1; then
          aa-status >> "${LOG_DIR}/tests-apparmor.logs"
        else
          echo "Failed to enable AppArmor - check kernel support" >> "${LOG_DIR}/tests-apparmor.logs"
        fi
      fi
          
      # Inter-service tests
      if hostname | grep -q white; then
        curl http://black.black.svc.cluster.local >> "${LOG_DIR}/test-curl.log" 2>&1
      else
        curl http://white.white.svc.cluster.local >> "${LOG_DIR}/test-curl.log" 2>&1
      fi
      
      sleep 5
    done